public enum Commands {
    ADDPERSON,
    ADDSHOW,
    ADDPARTICIPATION,
    PREMIERE,
    REMOVESHOW,
    TAGSHOW,
    INFOSHOW,
    RATESHOW,
    INFOPERSON,
    LISTSHOWSPERSON,
    LISTPARTICIPATIONS,
    LISTBESTSHOWS,
    LISTSHOWS,
    LISTTAGGEDSHOWS,
    QUIT,
    UNKNOWN
}
